import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Zap, Save, FolderOpen, Trash2, LayoutGrid, List,
  Sparkles, ArrowLeft, Search, X, RotateCcw, AlertTriangle,
  Activity, Download, Upload, Share2, Settings, Info,
  Undo2, RefreshCw, ArrowUpDown
} from 'lucide-react';
import type { TabData, TabGroupData, SessionData } from '../db';
import { saveSession, getSessions, deleteSession, saveWorkingState, loadWorkingState, clearWorkingState } from '../db';
import { groupTabsHeuristic, checkDeadLinks } from '../groupingEngine';
import { TabCard } from './TabCard';
import { v4 as uuidv4 } from 'uuid';

// Chrome API helper for extension context
function getChrome() {
  return (typeof window !== 'undefined' && (window as any).chrome) || null;
}

function isChromeExtension() {
  const chrome = getChrome();
  return chrome && chrome.tabs && chrome.tabs.create;
}

function safeDomain(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, '');
  } catch {
    return 'unknown';
  }
}

// Generate shareable standalone HTML from a session
function generateShareHTML(session: SessionData): string {
  const tabs = session.groups.flatMap(g => g.tabs);
  const groupsHtml = session.groups.map(g => `
    <section style="margin-bottom:32px;">
      <h2 style="font-size:18px;font-weight:600;color:#c084fc;margin:0 0 12px;padding-bottom:8px;border-bottom:1px solid #2e303a;">${g.name}</h2>
      <div style="display:flex;flex-direction:column;gap:8px;">
        ${g.tabs.map(t => `
          <a href="${t.url}" target="_blank" rel="noopener" style="display:flex;align-items:center;gap:12px;padding:12px 16px;background:#1f2028;border-radius:10px;text-decoration:none;color:#e2e2e8;transition:background 0.15s;" onmouseover="this.style.background='#2a2b36'" onmouseout="this.style.background='#1f2028'">
            <div style="width:32px;height:32px;border-radius:6px;background:linear-gradient(135deg,#7c3aed,#6d28d9);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:white;flex-shrink:0;">${t.domain.charAt(0).toUpperCase()}</div>
            <div style="min-width:0;">
              <div style="font-size:14px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${t.title || t.url}</div>
              <div style="font-size:11px;color:#71717a;margin-top:2px;">${t.domain}</div>
            </div>
          </a>
        `).join('')}
      </div>
    </section>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${session.name} — TabTamer Share</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; font-family: system-ui, -apple-system, sans-serif; background: #0f0f13; color: #e2e2e8; line-height: 1.5; }
    .container { max-width: 720px; margin: 0 auto; padding: 32px 20px; }
    header { margin-bottom: 32px; }
    h1 { font-size: 28px; font-weight: 600; margin: 0 0 8px; letter-spacing: -0.5px; }
    .meta { color: #71717a; font-size: 14px; }
    .badge { display: inline-flex; align-items: center; gap: 6px; padding: 4px 12px; background: rgba(192,132,252,0.12); color: #c084fc; border-radius: 20px; font-size: 12px; font-weight: 500; margin-top: 12px; }
    footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid #2e303a; text-align: center; color: #52525b; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>${session.name}</h1>
      <div class="meta">${tabs.length} tabs · ${session.groups.length} groups · ${new Date(session.createdAt).toLocaleDateString()}</div>
      <div class="badge">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>
        Shared with TabTamer
      </div>
    </header>
    ${groupsHtml}
    <footer>
      Generated by TabTamer — Smart tab organization, private & local.
    </footer>
  </div>
</body>
</html>`;
}

type ViewType = 'dashboard' | 'sessions' | 'settings';
type SortType = 'default' | 'name' | 'size' | 'recent';

export function Dashboard() {
  const [groups, setGroups] = useState<TabGroupData[]>([]);
  const [sessions, setSessions] = useState<SessionData[]>([]);
  const [view, setView] = useState<ViewType>('dashboard');
  const [isGrouping, setIsGrouping] = useState(false);
  const [search, setSearch] = useState('');
  const [sessionName, setSessionName] = useState('');
  const [showSave, setShowSave] = useState(false);
  const [checkingLinks, setCheckingLinks] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const [showShare, setShowShare] = useState<SessionData | null>(null);
  const [undoStack, setUndoStack] = useState<{ groups: TabGroupData[]; action: string }[]>([]);
  const [showUndo, setShowUndo] = useState(false);
  const [draggedGroupId, setDraggedGroupId] = useState<string | null>(null);
  const [dragOverGroupId, setDragOverGroupId] = useState<string | null>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  // Auto-save current working state with debounce
  useEffect(() => {
    const timeout = setTimeout(() => {
      if (groups.length > 0) {
        saveWorkingState(groups);
      }
    }, 1000);
    return () => clearTimeout(timeout);
  }, [groups]);

  // Load saved state on mount
  useEffect(() => {
    loadSessions();
    checkForCapture();
    loadAutoSavedState();
    // Check URL for view override
    const params = new URLSearchParams(window.location.search);
    const v = params.get('view');
    if (v === 'settings') setView('settings');

    // Keyboard shortcuts
    const handleKeyDown = (e: KeyboardEvent) => {
      // Ignore if typing in input
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;

      if (e.key === '/' && (view as string) === 'dashboard') {
        e.preventDefault();
        searchInputRef.current?.focus();
      } else if (e.key === 'Escape') {
        setSearch('');
        setShowSave(false);
        setShowShare(null);
      } else if (e.key === 'z' && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        handleUndo();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [view, undoStack]);

  useEffect(() => {
    if (toast) {
      const t = setTimeout(() => setToast(null), 2500);
      return () => clearTimeout(t);
    }
  }, [toast]);

  useEffect(() => {
    if (undoStack.length > 0) {
      setShowUndo(true);
      const t = setTimeout(() => setShowUndo(false), 3000);
      return () => clearTimeout(t);
    }
  }, [undoStack]);

  const loadSessions = async () => {
    const s = await getSessions();
    setSessions(s);
  };

  const loadAutoSavedState = async () => {
    const saved = await loadWorkingState();
    if (saved && saved.length > 0) {
      setGroups(saved);
      setToast('Restored unsaved work from last session');
    }
  };

  const checkForCapture = async () => {
    const urlParams = new URLSearchParams(window.location.search);
    if (urlParams.get('capture') === '1') {
      setTimeout(async () => {
        try {
          const mock = localStorage.getItem('tabtamer_capture_mock');
          if (mock) {
            const tabs: TabData[] = JSON.parse(mock);
            await runGrouping(tabs);
            localStorage.removeItem('tabtamer_capture_mock');
            return;
          }

          const ext = getChrome();
          if (ext && ext.storage?.local) {
            const data = await ext.storage.local.get([
              'tabtamer_capture',
              'tabtamer_captured_ids',
              'tabtamer_close_after_capture',
            ]);
            if (data.tabtamer_capture) {
              const tabs: TabData[] = data.tabtamer_capture.map((t: any) => ({
                ...t,
                domain: safeDomain(t.url),
                keywords: t.keywords || [],
                lastAccessed: Date.now(),
                clickCount: 0,
                isDuplicate: t.isDuplicate || false,
              }));
              await runGrouping(tabs);

              if (data.tabtamer_close_after_capture && data.tabtamer_captured_ids) {
                try {
                  await ext.tabs.remove(data.tabtamer_captured_ids);
                  setToast(`Closed ${data.tabtamer_captured_ids.length} tabs — organized in dashboard`);
                } catch {
                  setToast('Tabs organized. Some tabs could not be closed.');
                }
              } else {
                setToast('Tabs organized — originals still open');
              }

              await ext.storage.local.remove([
                'tabtamer_capture',
                'tabtamer_captured_ids',
                'tabtamer_close_after_capture',
              ]);
            }
          }
        } catch (e) {
          console.error('Capture error:', e);
        }
      }, 300);
    }
  };

  const runGrouping = async (tabs: TabData[]) => {
    setIsGrouping(true);
    await new Promise(r => setTimeout(r, 400));
    const grouped = groupTabsHeuristic(tabs);
    setGroups(grouped);
    setIsGrouping(false);
    setView('dashboard');
  };

  const handleReGroup = async () => {
    const allTabs = groups.flatMap(g => g.tabs);
    if (allTabs.length === 0) {
      setToast('No tabs to re-group');
      return;
    }
    pushUndo('Re-group tabs');
    await runGrouping(allTabs);
    setToast('Tabs re-grouped with AI');
  };

  const pushUndo = (action: string) => {
    setUndoStack(prev => [...prev.slice(-9), { groups: JSON.parse(JSON.stringify(groups)), action }]);
  };

  const handleUndo = () => {
    if (undoStack.length === 0) return;
    const last = undoStack.pop();
    if (last) {
      setGroups(last.groups);
      setToast(`Undid: ${last.action}`);
    }
  };

  const handleSort = (type: SortType) => {
    let sorted = [...groups];
    switch (type) {
      case 'name':
        sorted.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case 'size':
        sorted.sort((a, b) => b.tabs.length - a.tabs.length);
        break;
      case 'recent':
        // Sort by most recently accessed tab in group
        sorted.sort((a, b) => {
          const maxA = Math.max(...a.tabs.map(t => t.lastAccessed || 0));
          const maxB = Math.max(...b.tabs.map(t => t.lastAccessed || 0));
          return maxB - maxA;
        });
        break;
      default:
        // Keep original order
        break;
    }
    setGroups(sorted);
  };

  // Drag and drop handlers
  const handleDragStart = (_tabId: string, fromGroupId: string) => {
    setDraggedGroupId(fromGroupId);
  };

  const handleDragEnter = (groupId: string) => {
    if (draggedGroupId && draggedGroupId !== groupId) {
      setDragOverGroupId(groupId);
    }
  };

  const handleDragLeave = (_groupId: string) => {
    setDragOverGroupId(null);
  };

  const handleDrop = (tabId: string, fromGroupId: string, toGroupId: string) => {
    setDraggedGroupId(null);
    setDragOverGroupId(null);
    if (fromGroupId === toGroupId) return;
    pushUndo('Move tab');
    handleMoveTab(tabId, fromGroupId, toGroupId);
  };

  const handleCheckDeadLinks = async () => {
    setCheckingLinks(true);
    const allTabs = groups.flatMap(g => g.tabs);
    const checked = await checkDeadLinks(allTabs);
    let idx = 0;
    const updated = groups.map(g => ({
      ...g,
      tabs: g.tabs.map(() => checked[idx++]),
    }));
    setGroups(updated);
    setCheckingLinks(false);
    const deadCount = checked.filter(t => t.isDead).length;
    setToast(deadCount > 0 ? `Found ${deadCount} potentially dead links` : 'All links look healthy');
  };

  const handleLoadSession = (session: SessionData) => {
    pushUndo('Load session');
    setGroups(session.groups);
    setView('dashboard');
    setToast(`Loaded session: ${session.name}`);
  };

  const handleDeleteSession = async (id: string) => {
    await deleteSession(id);
    await loadSessions();
  };

  const handleDeleteGroup = (id: string) => {
    pushUndo('Delete group');
    setGroups(prev => prev.filter(g => g.id !== id));
  };

  const handleDeleteTab = (groupId: string, tabId: string) => {
    pushUndo('Delete tab');
    setGroups(prev => prev.map(g => {
      if (g.id !== groupId) return g;
      return { ...g, tabs: g.tabs.filter(t => t.id !== tabId) };
    }).filter(g => g.tabs.length > 0));
  };

  const handleRenameGroup = (id: string, name: string) => {
    pushUndo('Rename group');
    setGroups(prev => prev.map(g => g.id === id ? { ...g, name } : g));
  };

  // Drag-and-drop: move tab between groups
  const handleMoveTab = (tabId: string, fromGroupId: string, toGroupId: string) => {
    if (fromGroupId === toGroupId) return;
    pushUndo('Move tab');
    setGroups(prev => {
      const tab = prev.find(g => g.id === fromGroupId)?.tabs.find(t => t.id === tabId);
      if (!tab) return prev;
      return prev.map(g => {
        if (g.id === fromGroupId) return { ...g, tabs: g.tabs.filter(t => t.id !== tabId) };
        if (g.id === toGroupId) return { ...g, tabs: [...g.tabs, tab] };
        return g;
      }).filter(g => g.tabs.length > 0);
    });
  };

  const handleSaveSession = async () => {
    if (!sessionName.trim()) return;
    const session: SessionData = {
      id: uuidv4(),
      name: sessionName.trim(),
      groups,
      createdAt: Date.now(),
    };
    await saveSession(session);
    setShowSave(false);
    setSessionName('');
    await loadSessions();
    setToast('Session saved');
    // Clear auto-save after successful save
    await clearWorkingState();
  };

  const handleExportSessions = () => {
    const data = JSON.stringify(sessions, null, 2);
    const blob = new Blob([data], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `tabtamer-sessions-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setToast(`Exported ${sessions.length} sessions`);
  };

  const handleImportSessions = async () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (!file) return;
      try {
        const text = await file.text();
        const imported: SessionData[] = JSON.parse(text);
        for (const session of imported) {
          // Re-assign IDs to avoid collisions
          const newSession = { ...session, id: uuidv4(), createdAt: Date.now() };
          await saveSession(newSession);
        }
        await loadSessions();
        setToast(`Imported ${imported.length} sessions`);
      } catch {
        setToast('Import failed — invalid JSON');
      }
    };
    input.click();
  };

  const handleShareSession = (session: SessionData) => {
    setShowShare(session);
  };

  const handleDownloadShare = () => {
    if (!showShare) return;
    const html = generateShareHTML(showShare);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${showShare.name.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-tabtamer.html`;
    a.click();
    URL.revokeObjectURL(url);
    setToast('Shareable HTML downloaded');
  };

  const handleRestoreGroup = async (tabs: TabData[]) => {
    if (!isChromeExtension()) {
      setToast('Restore works from the Chrome extension only');
      return;
    }
    const ext = getChrome();
    for (const tab of tabs) {
      try {
        await ext.tabs.create({ url: tab.url, active: false });
      } catch (e) {
        console.error('Failed to restore tab:', tab.url, e);
      }
    }
    setToast(`Restored ${tabs.length} tabs`);
  };

  const handleRestoreAll = async () => {
    const allTabs = groups.flatMap(g => g.tabs);
    await handleRestoreGroup(allTabs);
  };

  const handleClearAllData = async () => {
    if (!confirm('Delete ALL saved sessions and current groups? This cannot be undone.')) return;
    for (const s of sessions) {
      await deleteSession(s.id);
    }
    setSessions([]);
    setGroups([]);
    await clearWorkingState();
    setToast('All data cleared');
  };

  const filteredGroups = groups.map(g => ({
    ...g,
    tabs: g.tabs.filter(t =>
      t.title.toLowerCase().includes(search.toLowerCase()) ||
      t.url.toLowerCase().includes(search.toLowerCase()) ||
      t.domain.toLowerCase().includes(search.toLowerCase())
    )
  })).filter(g => g.tabs.length > 0);

  const totalTabs = groups.reduce((sum, g) => sum + g.tabs.length, 0);
  const duplicateCount = groups.flatMap(g => g.tabs).filter(t => t.isDuplicate).length;

  return (
    <div className="min-h-screen bg-[#0f0f13] text-zinc-200">
      {/* Toast */}
      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed top-4 left-1/2 -translate-x-1/2 z-[200] px-4 py-2 bg-zinc-800 border border-zinc-700 rounded-xl shadow-xl text-sm flex items-center gap-2"
          >
            <Activity size={14} className="text-purple-400" />
            {toast}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Undo toast */}
      <AnimatePresence>
        {showUndo && undoStack.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed top-4 left-1/2 -translate-x-1/2 z-[200] px-4 py-2 bg-zinc-800 border border-zinc-700 rounded-xl shadow-xl text-sm flex items-center gap-3"
          >
            <button
              onClick={handleUndo}
              className="flex items-center gap-2 hover:text-purple-400 transition-colors"
            >
              <Undo2 size={14} />
              Undo {undoStack[undoStack.length - 1]?.action}
            </button>
            <span className="text-zinc-500">|</span>
            <span className="text-zinc-500 text-xs">Ctrl+Z</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Share modal */}
      <AnimatePresence>
        {showShare && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
            onClick={() => setShowShare(null)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={e => e.stopPropagation()}
              className="bg-zinc-800 border border-zinc-700 rounded-2xl p-6 w-full max-w-md shadow-2xl"
            >
              <h3 className="text-lg font-medium mb-2 flex items-center gap-2">
                <Share2 size={18} className="text-purple-400" />
                Share "{showShare.name}"
              </h3>
              <p className="text-sm text-zinc-400 mb-4">
                Generates a self-contained HTML file you can save, email, or host anywhere.
              </p>
              <div className="bg-zinc-900/50 rounded-lg p-3 mb-4 text-xs text-zinc-500 font-mono overflow-hidden">
                {showShare.groups.length} groups · {showShare.groups.reduce((s, g) => s + g.tabs.length, 0)} tabs
              </div>
              <div className="flex justify-end gap-2">
                <button
                  onClick={() => setShowShare(null)}
                  className="px-4 py-2 text-sm text-zinc-400 hover:text-zinc-200 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleDownloadShare}
                  className="px-4 py-2 bg-purple-600 hover:bg-purple-500 rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                >
                  <Download size={14} />
                  Download HTML
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header */}
      <header className="sticky top-0 z-50 bg-[#0f0f13]/80 backdrop-blur-xl border-b border-zinc-800/50">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center gap-4">
          <div className="flex items-center gap-2 shrink-0">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-500 to-violet-600 flex items-center justify-center">
              <Sparkles size={16} className="text-white" />
            </div>
            <h1 className="font-semibold text-lg tracking-tight">TabTamer</h1>
          </div>

          {(view as string) === 'dashboard' && (
            <>
              <div className="flex-1 max-w-md relative hidden sm:block">
                <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500" />
                <input
                  ref={searchInputRef}
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  placeholder="Search tabs... (press / to focus)"
                  className="w-full bg-zinc-800/60 border border-zinc-700/50 rounded-lg pl-9 pr-8 py-1.5 text-sm outline-none focus:border-purple-500/50 transition-colors placeholder:text-zinc-500"
                />
                {search && (
                  <button
                    onClick={() => setSearch('')}
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
                  >
                    <X size={14} />
                  </button>
                )}
              </div>

              <div className="flex items-center gap-2 ml-auto flex-wrap justify-end">
                {groups.length > 0 && (
                  <>
                    <span className="text-xs text-zinc-500 hidden md:inline">
                      {totalTabs} tabs · {groups.length} groups
                      {duplicateCount > 0 && ` · ${duplicateCount} duplicates`}
                    </span>
                    <button
                      onClick={handleReGroup}
                      disabled={isGrouping}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-500/15 hover:bg-purple-500/25 text-purple-300 rounded-lg text-sm transition-colors border border-purple-500/20 disabled:opacity-50"
                      title="Re-run AI grouping on current tabs"
                    >
                      <RefreshCw size={14} className={isGrouping ? 'animate-spin' : ''} />
                      <span className="hidden sm:inline">Re-group</span>
                    </button>
                    <button
                      onClick={handleRestoreAll}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-500/15 hover:bg-emerald-500/25 text-emerald-300 rounded-lg text-sm transition-colors border border-emerald-500/20"
                      title="Restore all tabs in browser"
                    >
                      <RotateCcw size={14} />
                      <span className="hidden sm:inline">Restore all</span>
                    </button>
                    <button
                      onClick={handleCheckDeadLinks}
                      disabled={checkingLinks}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 disabled:opacity-50 rounded-lg text-sm transition-colors border border-zinc-700/50"
                    >
                      <AlertTriangle size={14} />
                      <span className="hidden sm:inline">{checkingLinks ? 'Checking...' : 'Check links'}</span>
                    </button>
                    <button
                      onClick={() => setShowSave(true)}
                      className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm transition-colors border border-zinc-700/50"
                    >
                      <Save size={14} />
                      <span className="hidden sm:inline">Save</span>
                    </button>
                    <div className="relative">
                      <button
                        onClick={() => {
                          const menu = document.getElementById('sort-menu');
                          menu?.classList.toggle('hidden');
                        }}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm transition-colors border border-zinc-700/50"
                      >
                        <ArrowUpDown size={14} />
                        <span className="hidden sm:inline">Sort</span>
                      </button>
                      <div
                        id="sort-menu"
                        className="hidden absolute right-0 top-full mt-1 bg-zinc-800 border border-zinc-700 rounded-lg shadow-xl z-50 min-w-[120px]"
                      >
                        <button
                          onClick={() => { handleSort('default'); document.getElementById('sort-menu')?.classList.add('hidden'); }}
                          className="w-full px-3 py-2 text-left text-sm hover:bg-zinc-700 transition-colors"
                        >
                          Default
                        </button>
                        <button
                          onClick={() => { handleSort('name'); document.getElementById('sort-menu')?.classList.add('hidden'); }}
                          className="w-full px-3 py-2 text-left text-sm hover:bg-zinc-700 transition-colors"
                        >
                          By name
                        </button>
                        <button
                          onClick={() => { handleSort('size'); document.getElementById('sort-menu')?.classList.add('hidden'); }}
                          className="w-full px-3 py-2 text-left text-sm hover:bg-zinc-700 transition-colors"
                        >
                          By size
                        </button>
                        <button
                          onClick={() => { handleSort('recent'); document.getElementById('sort-menu')?.classList.add('hidden'); }}
                          className="w-full px-3 py-2 text-left text-sm hover:bg-zinc-700 transition-colors"
                        >
                          By recent
                        </button>
                      </div>
                    </div>
                  </>
                )}
                <button
                  onClick={() => setView('sessions')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm transition-colors border ${
                    (view as string) === 'sessions'
                      ? 'bg-purple-500/20 border-purple-500/30 text-purple-300'
                      : 'bg-zinc-800 hover:bg-zinc-700 border-zinc-700/50'
                  }`}
                >
                  <FolderOpen size={14} />
                  <span className="hidden sm:inline">Sessions</span>
                </button>
                <button
                  onClick={() => setView('settings')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm transition-colors border ${
                    (view as string) === 'settings'
                      ? 'bg-purple-500/20 border-purple-500/30 text-purple-300'
                      : 'bg-zinc-800 hover:bg-zinc-700 border-zinc-700/50'
                  }`}
                >
                  <Settings size={14} />
                </button>
              </div>
            </>
          )}

          {(view as string) !== 'dashboard' && (
            <button
              onClick={() => setView('dashboard')}
              className="flex items-center gap-1.5 px-3 py-1.5 ml-auto bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm transition-colors border border-zinc-700/50"
            >
              <ArrowLeft size={14} />
              Back
            </button>
          )}
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-6xl mx-auto px-4 py-6">
        <AnimatePresence mode="wait">
          {(view as string) === 'dashboard' && (
            <motion.div
              key="dashboard"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
            >
              {/* Empty state */}
              {groups.length === 0 && !isGrouping && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex flex-col items-center justify-center py-24 text-center"
                >
                  <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-purple-500/20 to-violet-500/10 flex items-center justify-center mb-6">
                    <Zap size={32} className="text-purple-400" />
                  </div>
                  <h2 className="text-2xl font-medium mb-2">Tame your tabs</h2>
                  <p className="text-zinc-400 max-w-md mb-8 leading-relaxed">
                    Capture your browser chaos into beautiful, auto-organized groups.
                    Choose to keep tabs open, close them to free RAM, or group them natively in Chrome.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-3">
                    <button
                      onClick={async () => {
                        const demoTabs: TabData[] = [
                          { id: '1', url: 'https://react.dev/reference/react', title: 'React Reference Overview', favicon: '', domain: 'react.dev', keywords: ['react'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '2', url: 'https://github.com/facebook/react/issues', title: 'Issues - facebook/react', favicon: '', domain: 'github.com', keywords: ['github', 'react'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '3', url: 'https://tailwindcss.com/docs/utility-classes', title: 'Utility-First Fundamentals', favicon: '', domain: 'tailwindcss.com', keywords: ['tailwind', 'css'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '4', url: 'https://stackoverflow.com/questions/123/react-hooks', title: 'How to use React Hooks properly', favicon: '', domain: 'stackoverflow.com', keywords: ['react', 'hooks'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '5', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API', title: 'Fetch API - Web APIs | MDN', favicon: '', domain: 'developer.mozilla.org', keywords: ['fetch', 'api'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '6', url: 'https://nextjs.org/docs/app-router', title: 'App Router - Next.js', favicon: '', domain: 'nextjs.org', keywords: ['nextjs'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '7', url: 'https://vercel.com/dashboard', title: 'Vercel Dashboard', favicon: '', domain: 'vercel.com', keywords: ['vercel', 'deploy'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '8', url: 'https://medium.com/@dev/typescript-tips', title: 'Advanced TypeScript Tips for 2024', favicon: '', domain: 'medium.com', keywords: ['typescript'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '9', url: 'https://news.ycombinator.com/item?id=12345', title: 'Show HN: New framework built on Rust', favicon: '', domain: 'news.ycombinator.com', keywords: ['hn'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '10', url: 'https://docs.python.org/3/library/asyncio.html', title: 'asyncio - Asynchronous I/O', favicon: '', domain: 'docs.python.org', keywords: ['python', 'asyncio'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '11', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: 'Never Gonna Give You Up', favicon: '', domain: 'youtube.com', keywords: ['video'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '12', url: 'https://redis.io/commands', title: 'Redis Commands Documentation', favicon: '', domain: 'redis.io', keywords: ['redis'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '13', url: 'https://github.com/facebook/react/pull/123', title: 'PR #123 - Fix hook bug in concurrent mode', favicon: '', domain: 'github.com', keywords: ['github', 'react', 'pr'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '14', url: 'https://github.com/facebook/react/issues/456', title: 'Issue #456 - useEffect warning when unmounting', favicon: '', domain: 'github.com', keywords: ['github', 'react', 'issue'], lastAccessed: Date.now(), clickCount: 0 },
                          { id: '15', url: 'https://rust-lang.github.io/rust-clippy/master/index.html', title: 'Rust Clippy Lints', favicon: '', domain: 'rust-lang.github.io', keywords: ['rust', 'clippy'], lastAccessed: Date.now(), clickCount: 0 },
                        ];
                        await runGrouping(demoTabs);
                      }}
                      className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-purple-600 to-violet-600 hover:from-purple-500 hover:to-violet-500 rounded-xl text-white font-medium transition-all shadow-lg shadow-purple-900/20"
                    >
                      <Sparkles size={18} />
                      Try demo (15 tabs)
                    </button>
                    <button
                      onClick={() => {
                        const input = prompt('Paste tab data (JSON array):');
                        if (!input) return;
                        try {
                          const tabs = JSON.parse(input);
                          runGrouping(tabs);
                        } catch {
                          alert('Invalid JSON');
                        }
                      }}
                      className="flex items-center gap-2 px-5 py-2.5 bg-zinc-800 hover:bg-zinc-700 rounded-xl text-sm transition-colors border border-zinc-700/50"
                    >
                      <LayoutGrid size={18} />
                      Import tabs
                    </button>
                  </div>
                  <p className="text-zinc-500 text-xs mt-6 max-w-sm">
                    Install the Chrome extension for the full experience: capture real tabs,
                    optionally close them to save RAM, group them natively in Chrome, and restore anytime.
                  </p>
                </motion.div>
              )}

              {/* Grouping animation */}
              {isGrouping && (
                <div className="flex flex-col items-center justify-center py-24">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ repeat: Infinity, duration: 1.5, ease: 'linear' }}
                    className="w-10 h-10 border-2 border-purple-500 border-t-transparent rounded-full mb-4"
                  />
                  <p className="text-zinc-400 animate-pulse">Organizing your tabs with smart grouping...</p>
                </div>
              )}

              {/* Groups grid */}
              {groups.length > 0 && !isGrouping && (
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                  {filteredGroups.map((group, i) => (
                    <TabCard
                      key={group.id}
                      group={group}
                      index={i}
                      onDeleteGroup={handleDeleteGroup}
                      onDeleteTab={handleDeleteTab}
                      onRenameGroup={handleRenameGroup}
                      onMoveTab={handleMoveTab}
                      onRestoreGroup={handleRestoreGroup}
                      otherGroups={groups.filter(g => g.id !== group.id).map(g => ({ id: g.id, name: g.name }))}
                      onDragStart={handleDragStart}
                      onDrop={handleDrop}
                      onDragEnter={handleDragEnter}
                      onDragLeave={handleDragLeave}
                      isDraggingOver={dragOverGroupId === group.id}
                    />
                  ))}
                </div>
              )}

              {groups.length > 0 && filteredGroups.length === 0 && !isGrouping && (
                <div className="text-center py-16 text-zinc-500">
                  No tabs match your search.
                </div>
              )}
            </motion.div>
          )}

          {(view as string) === 'sessions' && (
            <motion.div
              key="sessions"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-medium flex items-center gap-2">
                  <List size={20} className="text-purple-400" />
                  Saved Sessions
                </h2>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleImportSessions}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded-lg text-sm transition-colors border border-zinc-700/50"
                  >
                    <Upload size={14} />
                    <span className="hidden sm:inline">Import</span>
                  </button>
                  <button
                    onClick={handleExportSessions}
                    disabled={sessions.length === 0}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 disabled:opacity-40 rounded-lg text-sm transition-colors border border-zinc-700/50"
                  >
                    <Download size={14} />
                    <span className="hidden sm:inline">Export all</span>
                  </button>
                </div>
              </div>

              {sessions.length === 0 ? (
                <div className="text-center py-16 text-zinc-500">
                  No saved sessions yet. Organize some tabs and save them!
                </div>
              ) : (
                <div className="space-y-3">
                  {sessions.map(session => (
                    <motion.div
                      key={session.id}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      className="flex items-center justify-between p-4 bg-zinc-800/40 border border-zinc-700/30 rounded-xl hover:bg-zinc-800/60 transition-colors"
                    >
                      <div className="flex-1 min-w-0">
                        <h3 className="font-medium truncate">{session.name}</h3>
                        <p className="text-sm text-zinc-500">
                          {session.groups.length} groups, {session.groups.reduce((s, g) => s + g.tabs.length, 0)} tabs
                          {' '}· {new Date(session.createdAt).toLocaleDateString()}
                        </p>
                      </div>
                      <div className="flex items-center gap-2 shrink-0 ml-4">
                        <button
                          onClick={() => handleShareSession(session)}
                          className="p-1.5 hover:bg-purple-500/10 text-zinc-500 hover:text-purple-400 rounded-lg transition-colors"
                          title="Share as HTML"
                        >
                          <Share2 size={16} />
                        </button>
                        <button
                          onClick={() => handleLoadSession(session)}
                          className="px-3 py-1.5 bg-purple-500/20 hover:bg-purple-500/30 text-purple-300 rounded-lg text-sm transition-colors"
                        >
                          Load
                        </button>
                        <button
                          onClick={() => handleDeleteSession(session.id)}
                          className="p-1.5 hover:bg-red-500/10 text-zinc-500 hover:text-red-400 rounded-lg transition-colors"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          )}

          {(view as string) === 'settings' && (
            <motion.div
              key="settings"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
            >
              <h2 className="text-xl font-medium mb-6 flex items-center gap-2">
                <Settings size={20} className="text-purple-400" />
                Settings
              </h2>

              <div className="space-y-4 max-w-xl">
                <div className="p-4 bg-zinc-800/40 border border-zinc-700/30 rounded-xl">
                  <h3 className="font-medium mb-2 flex items-center gap-2">
                    <Info size={16} className="text-zinc-500" />
                    About TabTamer
                  </h3>
                  <p className="text-sm text-zinc-400 leading-relaxed">
                    TabTamer uses a hybrid grouping engine: domain rules, keyword extraction,
                    and semantic title-similarity clustering. All processing happens locally
                    in your browser. No data is sent to any server.
                  </p>
                </div>

                <div className="p-4 bg-zinc-800/40 border border-zinc-700/30 rounded-xl">
                  <h3 className="font-medium mb-3">Data Management</h3>
                  <div className="flex flex-wrap gap-2">
                    <button
                      onClick={handleExportSessions}
                      disabled={sessions.length === 0}
                      className="flex items-center gap-2 px-4 py-2 bg-zinc-700/50 hover:bg-zinc-700 disabled:opacity-40 rounded-lg text-sm transition-colors"
                    >
                      <Download size={14} />
                      Export sessions
                    </button>
                    <button
                      onClick={handleImportSessions}
                      className="flex items-center gap-2 px-4 py-2 bg-zinc-700/50 hover:bg-zinc-700 rounded-lg text-sm transition-colors"
                    >
                      <Upload size={14} />
                      Import sessions
                    </button>
                    <button
                      onClick={handleClearAllData}
                      className="flex items-center gap-2 px-4 py-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 rounded-lg text-sm transition-colors"
                    >
                      <Trash2 size={14} />
                      Clear all data
                    </button>
                  </div>
                  <p className="text-xs text-zinc-500 mt-2">
                    {sessions.length} session{sessions.length !== 1 ? 's' : ''} stored locally
                  </p>
                </div>

                <div className="p-4 bg-zinc-800/40 border border-zinc-700/30 rounded-xl">
                  <h3 className="font-medium mb-2">Keyboard Shortcuts</h3>
                  <div className="text-sm text-zinc-400 space-y-1">
                    <div className="flex justify-between">
                      <span>Open TabTamer popup</span>
                      <kbd className="px-2 py-0.5 bg-zinc-700 rounded text-xs font-mono">Ctrl+Shift+Y</kbd>
                    </div>
                    <div className="flex justify-between">
                      <span>Focus search</span>
                      <kbd className="px-2 py-0.5 bg-zinc-700 rounded text-xs font-mono">/</kbd>
                    </div>
                    <div className="flex justify-between">
                      <span>Clear search / close modals</span>
                      <kbd className="px-2 py-0.5 bg-zinc-700 rounded text-xs font-mono">Esc</kbd>
                    </div>
                    <div className="flex justify-between">
                      <span>Undo last action</span>
                      <kbd className="px-2 py-0.5 bg-zinc-700 rounded text-xs font-mono">Ctrl+Z</kbd>
                    </div>
                  </div>
                </div>

                <div className="p-4 bg-zinc-800/40 border border-zinc-700/30 rounded-xl">
                  <h3 className="font-medium mb-2">Extension Features</h3>
                  <ul className="text-sm text-zinc-400 space-y-1 list-disc list-inside">
                    <li>Capture and organize all open tabs</li>
                    <li>Optionally close tabs to free RAM after capture</li>
                    <li>Group tabs natively in Chrome (domain-based)</li>
                    <li>Restore tabs individually or in groups</li>
                    <li>Dead link detection with one click</li>
                    <li>Duplicate tab detection and flagging</li>
                    <li>Save, export, import, and share sessions</li>
                    <li>Auto-save unsaved work (crash recovery)</li>
                    <li>Undo system for deleted groups/tabs</li>
                    <li>Re-run AI grouping on current tabs</li>
                    <li>Sort groups by name, size, or recency</li>
                  </ul>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Save session modal */}
      <AnimatePresence>
        {showSave && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"
            onClick={() => setShowSave(false)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={e => e.stopPropagation()}
              className="bg-zinc-800 border border-zinc-700 rounded-2xl p-6 w-full max-w-sm shadow-2xl"
            >
              <h3 className="text-lg font-medium mb-4">Save Session</h3>
              <input
                value={sessionName}
                onChange={e => setSessionName(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleSaveSession()}
                placeholder="e.g. React research session"
                autoFocus
                className="w-full bg-zinc-700/50 border border-zinc-600 rounded-lg px-3 py-2 text-sm outline-none focus:border-purple-500/50 mb-4 placeholder:text-zinc-500"
              />
              <div className="flex justify-end gap-2">
                <button
                  onClick={() => setShowSave(false)}
                  className="px-4 py-2 text-sm text-zinc-400 hover:text-zinc-200 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSaveSession}
                  disabled={!sessionName.trim()}
                  className="px-4 py-2 bg-purple-600 hover:bg-purple-500 disabled:opacity-40 disabled:hover:bg-purple-600 rounded-lg text-sm font-medium transition-colors"
                >
                  Save
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
